### ISSUE TITLE
Error: listen EADDRINUSE

### ISSUE THREAD

**Issue by ajisek** [smashah/sulla#152]
**Describe the bug**
I get an error when running ```http.createserver```

**create() code**
This is the code you use to create the client. e.g
```javascript
sulla.create('SESSION', {executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'}).then(client => start(client));
```

**Expected behavior**
I want to run the ```http.createserver().listen(80)``` in function ```start```, 
like this code
```javascript
function start(client) {
  client.onMessage(async message => {
    const server = http.createServer();
    server.on('request', (request, response) => {
      response.writeHead(200, {'Content-Type': 'application/json'});
      var q = url.parse(request.url, true).query;
      var txt = q.pesan;
      response.end(txt);
      console.log(q);
      sendText(GROUP_ID', q.pesan);
  });
}
```
so when I access the server, sulla can send messages directly to the destination ie ```GROUP_ID```,
But I get an error like this : 
```Error: listen EADDRINUSE: address already in use :::80```
I also tried various ```PORT``` but got the same error

**DEBUG INFO**
```
Debug Info {
  WA_VERSION: '0.4.930',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.29',
  BROWSER_VERSION: 'HeadlessChrome/80.0.3987.122'
}
```

**Full of the error**
```
√ Authenticating
√ WAPI Reinjected
√ Whatsapp is ready
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (net.js:1306:16)
    at listenInCluster (net.js:1354:12)
    at Server.listen (net.js:1442:7)
    at D:\bot-whtasapp\index.js:57:8
    at D:\bot-whtasapp\node_modules\sulla-hotfix\dist\api\whatsapp.js:73:20
    at Page._onBindingCalled (D:\bot-whtasapp\node_modules\sulla-hotfix\node_modules\puppeteer\lib\Page.js:561:56)
    at CDPSession.<anonymous> (D:\bot-whtasapp\node_modules\sulla-hotfix\node_modules\puppeteer\lib\Page.js:121:54)
    at CDPSession.emit (events.js:223:5)
    at CDPSession._onMessage (D:\bot-whtasapp\node_modules\sulla-hotfix\node_modules\puppeteer\lib\Connection.js:200:12)
    at Connection._onMessage (D:\bot-whtasapp\node_modules\sulla-hotfix\node_modules\puppeteer\lib\Connection.js:112:17)
    at WebSocket.<anonymous> (D:\bot-whtasapp\node_modules\sulla-hotfix\node_modules\puppeteer\lib\WebSocketTransport.js:44:24)
    at WebSocket.onMessage (D:\bot-whtasapp\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:223:5)
    at Receiver.receiverOnMessage (D:\bot-whtasapp\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:223:5)
    at Receiver.dataMessage (D:\bot-whtasapp\node_modules\ws\lib\receiver.js:422:14)
    at Receiver.getData (D:\bot-whtasapp\node_modules\ws\lib\receiver.js:352:17)
    at Receiver.startLoop (D:\bot-whtasapp\node_modules\ws\lib\receiver.js:138:22)
    at Receiver._write (D:\bot-whtasapp\node_modules\ws\lib\receiver.js:74:10)
    at doWrite (_stream_writable.js:435:12)
    at writeOrBuffer (_stream_writable.js:419:5)
    at Receiver.Writable.write (_stream_writable.js:309:11)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1333:8)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 80
}
```

**Comment by smashah** [comment]
umm use a different port when creating the server, port 80 is already in use. This is not an issue with sulla. Please learn how to use [express](https://expressjs.com/).
