### ISSUE TITLE
 Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by jesusvalverde** [smashah/sulla#169]
**Describe the bug**
 node  test.ts

⠇ Initializing whatsapp(node:1790) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of undefined
    at /home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:247:35
    at step (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:33:23)
    at Object.next (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:14:53)
    at /home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:4:12)
    at kill (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:240:33)
    at Object.<anonymous> (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:230:32)
    at step (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:33:23)
    at Object.throw (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:14:53)
    at rejected (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:6:65)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1790) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠼ Initializing whatsap

**Steps to Reproduce**
Install a fresh AWS server Ubutun 18, done all update  and upgrade
install lxde and xrdp

Install npm 3.5.2
Install --->npm i --save sulla-hotfix
ts-node, typescript, p-queue, fs, wa-decrypt, axios, crypto, node-fetch 

(all steps work on older version)

**create() code**
Used test

const sulla = require('sulla-hotfix');
sulla.create().then(client => start(client));
function start(client) {
  client.onMessage(message => {
    if (message.body === 'Hi') {
      client.sendText(message.from, '👋 Hello from sulla!');
    }
  });
}

**Expected behavior**
No start ...just spining.

**DEBUG INFO**
No debug info...stick over "Initializin whatsapp"

**Screenshots**

**Host (please complete the following information):**
AWS Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-1057-aws x86_64)

**Additional context**

**Comment by jesusvalverde** [comment]
Install 
npm i sulla-hotfix@1.7.35

And work , but missing al the updates

**Comment by marcelocecin** [comment]
try to use https://www.npmjs.com/package/ts-node

**Comment by smashah** [comment]
@jesusvalverde this error is due to the kill function being called. I fixed this in v1.8.9 but that is seperate from a situation where the program is getting stuck on initializing whatsapp. I also have this runnning on ubuntu and it's working ok. Can you try latest version and report back thanks.

![release](https://user-images.githubusercontent.com/5903821/75934256-e2f24680-5e73-11ea-974a-496fddb9be5e.png)

**Comment by smashah** [comment]
Closing for now, thanks.

**Comment by jesusvalverde** [comment]
Nop.... new server, same instalation process, same demo typescript and new sula-hotfix and having 
using node test.ts or  ts-node test.ts


⠴ Initializing whatsapp(node:2066) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'browser' of undefined
    at /home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:253:29
    at step (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:33:23)
    at Object.next (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:14:53)
    at /home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:4:12)
    at kill (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:240:33)
    at Object.<anonymous> (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:230:32)
    at step (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:33:23)
    at Object.throw (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:14:53)
    at rejected (/home/ubuntu/node_modules/sulla-hotfix/dist/controllers/initializer.js:6:65)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:2066) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2066) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

if I do downgrade to npm i sulla-hotfix@1.7.35  all works fine 

node test.ts
✔ Initializing whatsapp
Debug Info { WA_VERSION: '0.4.1296',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.35',
  BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0',
  BROWSER_ID: 'KSBu2VfJ9kVspcr3o0a3jQ==' }
ℹ Authenticate to continue
✔ Loading QR

**Comment by smashah** [comment]
@jesusvalverde Please use the latest version in a fresh project folder. If that doesnt work please fill in a new issue template properly.

You can also try this:
https://github.com/smashah/sulla/issues/90#issuecomment-595241363
