### ISSUE TITLE
Error "sulla-hotfix": "^1.2.11" version after getAllMessagesInChat method

### ISSUE THREAD

**Issue by rfscheidt** [smashah/sulla#17]
Hello,

I'm trying to use the 1.2.11 version and the method bellow are getting error:
- getAllMessagesInChat
- getGroupMembersId

Message error:

(node:49060) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'participants' of undefined
    at Object.window.WAPI._getGroupParticipants (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/lib/wapi.js:548:21)
    at async Object.window.WAPI.getGroupParticipantIDs (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/lib/wapi.js:559:21)
    at ExecutionContext._evaluateInternal (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/Page.js:863:43)
    at Page.<anonymous> (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/helper.js:112:23)
    at Whatsapp.<anonymous> (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/api/whatsapp.js:164:50)
    at step (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/api/whatsapp.js:33:23)
    at Object.next (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/api/whatsapp.js:14:53)
    at /Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/api/whatsapp.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/api/whatsapp.js:4:12)
    at Whatsapp.getGroupMembersId (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/api/whatsapp.js:161:16)
    at /Users/foka/dev/workspace-estudos/whatsapp/src/router/whatsrouter.js:53:16
    at Layer.handle [as handle_request] (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/express/lib/router/route.js:137:13)

**Comment by smashah** [comment]
Are you checking a broadcast? Can you confirm our working for a group please

**Comment by rfscheidt** [comment]
I'm justing calling the method, like that:

router.get("/msg/retrieve/:ident/", function(req, res) {
        client.getAllMessagesInChat(req.params.ident, true, true).then(chats => {
            res.send(JSON.stringify(chats));
        });
});

    router.get("/msg/retrieve/groups/members/:ident/", function(req, res) {
        client.getGroupMembersId(req.params.ident).then(chats => {
            res.send(JSON.stringify(chats));
        });
    });

When I call this methods I got this error:

(node:51296) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'participants' of undefined
    at Object.window.WAPI._getGroupParticipants (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/lib/wapi.js:548:21)
    at async Object.window.WAPI.getGroupParticipantIDs (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/lib/wapi.js:559:21)
    at ExecutionContext._evaluateInternal (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/puppeteer/lib/Page.js:863:43)

I have another methos that works fine:

    router.get("/msg/send/:numero/:msg/", function(req, res) {
        client.sendText(req.params.numero + '@c.us',req.params.msg);
        res.send('OK');
    });

    router.get("/msg/retrieve/read/", function(req, res) {
        client.getAllChats(false).then(chats => {
            res.send(JSON.stringify(chats));
        });
    });

    router.get("/msg/retrieve/unread/", function(req, res) {
        client.getAllChats(true).then(chats => {
            res.send(JSON.stringify(chats));
        });
    });

**Comment by smashah** [comment]
@rfscheidt I've just tested this on both a broadcast and a group and it works fine. I only get this error when entering an invalid chatId.

Make sure your chatId looks like this

215678234342-123123123123@g.us

or

1341932128637@broadcast

**Comment by rfscheidt** [comment]
yes, you are right... I'm putting invalid chatId, I'm sorry and thank you!
