### ISSUE TITLE
TypeError: Cannot read property 'sendMessage' of undefined

### ISSUE THREAD

**Issue by LucasDibz** [smashah/sulla#18]
Tried sending an text today, error thrown was 
`(node:6383) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'sendMessage' of undefined
    
at Object.window.WAPI.getChat (/home/menudib/Desktop/Chatbot/node_modules/sulla-hotfix/dist/lib/wapi.js:289:32)
    
at Object.window.WAPI.sendSeen (/home/menudib/Desktop/Chatbot/node_modules/sulla-hotfix/dist/lib/wapi.js:828:28)
    
at __puppeteer_evaluation_script__:3:34`

**Comment by LucasDibz** [comment]
Was missing state code into contact number. dumbme
