### ISSUE TITLE
Block Contact

### ISSUE THREAD

**Issue by razisek** [smashah/sulla#277]
**Expected behavior**
How can I'm block contacts with sulla-hotfix?

**create() code**
This is the code you use to create the client. e.g
```javascript
sulla.create('SESSION', {executablePath: '/usr/bin/google-chrome-stable'}).then(client => start(client));
```

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '0.4.2088',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.8.30',
  BROWSER_VERSION: 'HeadlessChrome/80.0.3987.162'
}
```

**Host (please complete the following information):**

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.36](https://github.com/smashah/sulla/compare/1.8.35...1.8.36) (2020-04-05)

- Release 1.8.36 [`2b2f322`](https://github.com/smashah/sulla/commit/2b2f32284b00813f0e32e8278cb567a26cf646a2)
- implemented `contactBlock` and `contactUnblock` #277 [`f57df3a`](https://github.com/smashah/sulla/commit/f57df3a67b41a061bad8d00f65ef8085da379646)

**Comment by smashah** [comment]
@razisek you can now try:

```javascript
//block contact
client.contactBlock('4477777777777@c.us')

//unblock contact
client.contactUnblock('4477777777777@c.us')
```

https://smashah.github.io/sulla/classes/whatsapp.html#contactblock

Please report back if this worked for you. Thanks.

**Comment by razisek** [comment]
@smashah 
I have already updated to version 1.8.36, but I get an error like this after authentication.
```
✔ Initializing whatsapp
Debug Info {
  WA_VERSION: '0.4.2088',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.8.36',
  BROWSER_VERSION: 'Chrome/80.0.3987.163'
}
✔ Authenticated
✔ WAPI Reinjected
✔ Whatsapp is ready
(node:6197) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'models' of undefined
    at eval (eval at <anonymous> (:3:40), <anonymous>:1:14)
    at __puppeteer_evaluation_script__:3:40
    at Array.filter (<anonymous>)
    at __puppeteer_evaluation_script__:2:46
    at ExecutionContext._evaluateInternal (/media/azis/WIN/bot-whtasapp/node_modules/sulla-hotfix/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/media/azis/WIN/bot-whtasapp/node_modules/sulla-hotfix/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/media/azis/WIN/bot-whtasapp/node_modules/sulla-hotfix/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/media/azis/WIN/bot-whtasapp/node_modules/sulla-hotfix/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/media/azis/WIN/bot-whtasapp/node_modules/sulla-hotfix/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/media/azis/WIN/bot-whtasapp/node_modules/sulla-hotfix/node_modules/puppeteer/lib/Page.js:860:43)
    at Page.<anonymous> (/media/azis/WIN/bot-whtasapp/node_modules/sulla-hotfix/node_modules/puppeteer/lib/helper.js:112:23)
    at Object.<anonymous> (/media/azis/WIN/bot-whtasapp/node_modules/sulla-hotfix/dist/controllers/initializer.js:229:39)
    at step (/media/azis/WIN/bot-whtasapp/node_modules/sulla-hotfix/dist/controllers/initializer.js:44:23)
    at Object.next (/media/azis/WIN/bot-whtasapp/node_modules/sulla-hotfix/dist/controllers/initializer.js:25:53)
    at fulfilled (/media/azis/WIN/bot-whtasapp/node_modules/sulla-hotfix/dist/controllers/initializer.js:16:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6197) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6197) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by smashah** [comment]
@razisek try version 1.8.37

**Comment by razisek** [comment]
its work, Thank you so much
