### ISSUE TITLE
 EV Evaluation failed: TypeError: Cannot read property 'models' of undefined

### ISSUE THREAD

**Issue by hamid512** [smashah/sulla#278]
**Describe the bug**

**Steps to Reproduce**
1. Just running the demo only after authentication(scanning qr)

**create() code**
This is the code you use to create the client. e.g
Same code as demo index.ts

**Expected behavior**
Working demo

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
---------
EV Evaluation failed: TypeError: Cannot read property 'models' of undefined
    at eval (eval at <anonymous> (:3:40), <anonymous>:1:14)
    at __puppeteer_evaluation_script__:3:40
    at Array.filter (<anonymous>)
    at __puppeteer_evaluation_script__:2:46 session1 STARTUP
----------
(node:42807) UnhandledPromiseRejectionWarning: Error: Protocol error (Runtime.callFunctionOn): Target closed.
    at /Users/tawfiqladen/finworker/random2/sulla/node_modules/puppeteer/lib/Connection.js:183:56
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/tawfiqladen/finworker/random2/sulla/node_modules/puppeteer/lib/Connection.js:182:12)
    at ExecutionContext._evaluateInternal (/Users/tawfiqladen/finworker/random2/sulla/node_modules/puppeteer/lib/ExecutionContext.js:107:44)
    at ExecutionContext.evaluateHandle (/Users/tawfiqladen/finworker/random2/sulla/node_modules/puppeteer/lib/ExecutionContext.js:57:17)
    at ExecutionContext.<anonymous> (/Users/tawfiqladen/finworker/random2/sulla/node_modules/puppeteer/lib/helper.js:112:23)
    at WaitTask.rerun (/Users/tawfiqladen/finworker/random2/sulla/node_modules/puppeteer/lib/DOMWorld.js:570:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/tawfiqladen/finworker/random2/sulla/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.waitForSelector (/Users/tawfiqladen/finworker/random2/sulla/node_modules/puppeteer/lib/Page.js:1122:29)
    at Object.<anonymous> (/Users/tawfiqladen/finworker/random2/sulla/src/controllers/auth.ts:51:16)
    at step (/Users/tawfiqladen/finworker/random2/sulla/src/controllers/auth.ts:33:23)
    at Object.next (/Users/tawfiqladen/finworker/random2/sulla/src/controllers/auth.ts:14:53)
    at fulfilled (/Users/tawfiqladen/finworker/random2/sulla/src/controllers/auth.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:42807) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:42807) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error Evaluation failed: TypeError: Cannot read property 'models' of undefined
    at eval (eval at <anonymous> (:3:40), <anonymous>:1:14)
    at __puppeteer_evaluation_script__:3:40
    at Array.filter (<anonymous>)
    at __puppeteer_evaluation_script__:2:46
mb514:demo tawfiqladen$ 
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
Mac OS using node v12.13.0

**Additional context**

**Comment by darkclaude** [comment]
yes I have the same issues as well

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.37](https://github.com/smashah/sulla/compare/1.8.36...1.8.37) (2020-04-06)

- Release 1.8.37 [`fe6952f`](https://github.com/smashah/sulla/commit/fe6952fa9d02d3cd7c03c235e9d4f6ba289951d8)
- fix `models is undefined` #277 #278 [`558f7ec`](https://github.com/smashah/sulla/commit/558f7eca89cbb97cab92ab99a19219ee584df04c)

**Comment by hamid512** [comment]
issues fixed thanks

**Comment by hamid512** [comment]
your work is good, any idea when we can use the isOnline to know if people are online?
