### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'sendMessage' of undefined

### ISSUE THREAD

**Issue by habibshahid** [smashah/sulla#28]
Hey I am getting the following error while getting messages using chat id

``
const chatMessages = await client.getAllMessagesInChat(
			{chatId: chat.id, includeMe: true, includeNotifications: true}
		).then(message => {
			console.log(message);
		}).catch((error) => {
			console.error(error);
		});
``
can you please help / guide; what am I doing wrong?

``Error: Evaluation failed: TypeError: Cannot read property 'sendMessage' of undefined
    at Object.window.WAPI.getChat (C:\wamp64\www\sulla-hotfix\node_modules\sulla-hotfix\dist\lib\wapi.js:289:32)
    at Object.window.WAPI.getAllMessagesInChat (C:\wamp64\www\sulla-hotfix\node_modules\sulla-hotfix\dist\lib\wapi.js:618:23)
    at __puppeteer_evaluation_script__:3:41
    at ExecutionContext._evaluateInternal (C:\wamp64\www\sulla-hotfix\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\wamp64\www\sulla-hotfix\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (C:\wamp64\www\sulla-hotfix\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at <anonymous>
  -- ASYNC --
    at Frame.<anonymous> (C:\wamp64\www\sulla-hotfix\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (C:\wamp64\www\sulla-hotfix\node_modules\puppeteer\lib\Page.js:863:43)
    at Page.<anonymous> (C:\wamp64\www\sulla-hotfix\node_modules\puppeteer\lib\helper.js:112:23)
    at Whatsapp.<anonymous> (C:\wamp64\www\sulla-hotfix\node_modules\sulla-hotfix\dist\api\whatsapp.js:245:50)
    at step (C:\wamp64\www\sulla-hotfix\node_modules\sulla-hotfix\dist\api\whatsapp.js:33:23)
    at Object.next (C:\wamp64\www\sulla-hotfix\node_modules\sulla-hotfix\dist\api\whatsapp.js:14:53)
    at C:\wamp64\www\sulla-hotfix\node_modules\sulla-hotfix\dist\api\whatsapp.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\wamp64\www\sulla-hotfix\node_modules\sulla-hotfix\dist\api\whatsapp.js:4:12)
    at Whatsapp.getAllMessagesInChat (C:\wamp64\www\sulla-hotfix\node_modules\sulla-hotfix\dist\api\whatsapp.js:242:16)
    at allChats.forEach (C:\wamp64\www\sulla-hotfix\index.js:16:37)
    at Array.forEach (<anonymous>)
    at start (C:\wamp64\www\sulla-hotfix\index.js:15:11)
    at <anonymous>``

**Comment by paramirez** [comment]
https://github.com/Theblood/Wapi_NEW/blob/master/wapi.js

**Comment by habibshahid** [comment]
Thank you for the quick response. But its the same error.

**Comment by smashah** [comment]
@habibshahid please make sure you are using the latest version 1.2.15. thanks

**Comment by smashah** [comment]
Also you do not need to wrap the parameters in am object

```
const chatMessages = await client.getAllMessagesInChat(chat.id, true, includeNotifications)
```

**Comment by habibshahid** [comment]
Thank you for your help. Got it working
