### ISSUE TITLE
Error Page crash

### ISSUE THREAD

**Issue by mrbarnk** [smashah/sulla#59]
I always get this error here. 

`
Error: Page crashed!
    at Page._onTargetCrashed (/root/waap/node_modules/puppeteer/lib/Page.js:216:24)
    at CDPSession.<anonymous> (/root/waap/node_modules/puppeteer/lib/Page.js:124:56)
    at CDPSession.emit (events.js:305:20)
    at CDPSession._onMessage (/root/waap/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/root/waap/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocket.<anonymous> (/root/waap/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/root/waap/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:305:20)
    at Receiver.receiverOnMessage (/root/waap/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:305:20)
    at Receiver.dataMessage (/root/waap/node_modules/ws/lib/receiver.js:422:14)
    at Receiver.getData (/root/waap/node_modules/ws/lib/receiver.js:352:17)
    at Receiver.startLoop (/root/waap/node_modules/ws/lib/receiver.js:138:22)
    at Receiver._write (/root/waap/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:464:12)
    at writeOrBuffer (_stream_writable.js:446:5)
    at Receiver.Writable.write (_stream_writable.js:326:11)
    at Socket.socketOnData (/root/waap/node_modules/ws/lib/websocket.js:864:35)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
    at Socket.Readable.push (_stream_readable.js:250:10)
`

and it doesnt crash the container when this happens. It just pile up unread messages.

**Comment by smashah** [comment]
Duplicate #44
