### ISSUE TITLE
ReferenceError: webpackJsonp is not defined

### ISSUE THREAD

**Issue by azisekk** [smashah/sulla#75]
I'm having an error when trying to start a session with sulla.

```
D:\user\project\sulla>node index.js
√ Initializing whatsapp
i Authenticate to continue
√ Loading QR

(node:8884) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: webpackJsonp is not defined
    at __puppeteer_evaluation_script__:3:29
    at ExecutionContext._evaluateInternal ({PATH}\node_modules\sulla-hotfix\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async ExecutionContext.evaluate ({PATH}\node_modules\sulla-hotfix\node_modules\puppeteer\lib\ExecutionContext.js:48:12)
  -- ASYNC --
    at ExecutionContext.<anonymous> ({PATH}\node_modules\sulla-hotfix\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate ({PATH}\node_modules\sulla-hotfix\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
  -- ASYNC --
    at Frame.<anonymous> ({PATH}\node_modules\sulla-hotfix\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate ({PATH}\node_modules\sulla-hotfix\node_modules\puppeteer\lib\Page.js:858:43)
    at Page.<anonymous> ({PATH}\node_modules\sulla-hotfix\node_modules\puppeteer\lib\helper.js:112:23)
    at Object.<anonymous> ({PATH}\node_modules\sulla-hotfix\dist\controllers\auth.js:81:43)
    at step ({PATH}\node_modules\sulla-hotfix\dist\controllers\auth.js:33:23)
    at Object.next ({PATH}\node_modules\sulla-hotfix\dist\controllers\auth.js:14:53)
    at {PATH}\node_modules\sulla-hotfix\dist\controllers\auth.js:8:71
    at new Promise (<anonymous>)
    at __awaiter ({PATH}\node_modules\sulla-hotfix\dist\controllers\auth.js:4:12)
    at Object.retrieveQR ({PATH}\node_modules\sulla-hotfix\dist\controllers\auth.js:77:12)
    at Object.<anonymous> ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:76:55)
    at step ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:33:23)
    at Object.next ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:14:53)
    at {PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:4:12)
    at qrLoop ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:69:51)
    at Object.<anonymous> ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:96:21)
    at step ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:33:23)
    at Object.next ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:14:53)
    at fulfilled ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:5:58)
    at runMicrotasks (<anonymous>)
  -- ASYNC --
    at Page.<anonymous> ({PATH}\node_modules\sulla-hotfix\node_modules\puppeteer\lib\helper.js:111:15)
    at Object.<anonymous> ({PATH}\node_modules\sulla-hotfix\dist\controllers\auth.js:81:43)
    at step ({PATH}\node_modules\sulla-hotfix\dist\controllers\auth.js:33:23)
    at Object.next ({PATH}\node_modules\sulla-hotfix\dist\controllers\auth.js:14:53)
    at {PATH}\node_modules\sulla-hotfix\dist\controllers\auth.js:8:71
    at new Promise (<anonymous>)
    at __awaiter ({PATH}\node_modules\sulla-hotfix\dist\controllers\auth.js:4:12)
    at Object.retrieveQR ({PATH}\node_modules\sulla-hotfix\dist\controllers\auth.js:77:12)
    at Object.<anonymous> ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:76:55)
    at step ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:33:23)
    at Object.next ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:14:53)
    at {PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:4:12)
    at qrLoop ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:69:51)
    at Object.<anonymous> ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:96:21)
    at step ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:33:23)
    at Object.next ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:14:53)
    at fulfilled ({PATH}\node_modules\sulla-hotfix\dist\controllers\initializer.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:8884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

This error occurs when running index.js after exiting the session and running the session again. in the first session it's normal, but there is an error like that after the session

**Comment by azisekk** [comment]
Solved,
This is the same as the issue #71

**Comment by dogcalas** [comment]
How do you solved this issue?, I didn't find any solution in #71. Every time I restart with the same session name, this error occurs.

**Comment by smashah** [comment]
@dogcalas in v1.6.12 it will not throw the same error. However, the reason webpackJsonP is undefined from the start is because Facebook has most likely blocked the session from the beginning so it's good to make sure you are following best practices in the readme.

**Comment by ramonck** [comment]
This has happened to me multiple times even following the best practices, there's some other caviats they're taking into consideration before blocking. I think when we try multiple times in a very short amount of time to authenticate or scan teh QRCode they're taking that more into consideration before blocking.
