### ISSUE TITLE
Exception "Cannot read property 'call' of undefined"

### ISSUE THREAD

**Issue by mmc16** [smashah/sulla#81]
I am getting this exception; `(node:11368) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'call' of undefined`

I receive these messages, and then the exception is thrown, without showing the qrcode
✔ Initializing whatsapp
ℹ Authenticate to continue
✔ Loading QR

**The modules I am using:**
`express: ^4.17.1 `
`sulla-hotfix: ^1.6.10`
`ws: ^7.2.1`

**Chrome screeshot:**
![screenshot](https://user-images.githubusercontent.com/27312683/73460093-a4d6a400-4356-11ea-92e1-fd028d7c0e8b.png)

**Error Log:**
```bash
Server started on port 8080
✔ Initializing whatsapp
ℹ Authenticate to continue
✔ Loading QR

(node:11591) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'call' of undefined
    at t (https://web.whatsapp.com/progress.b2236901fec802a99807.js:2:412)
    at window.webpackJsonp (https://web.whatsapp.com/progress.b2236901fec802a99807.js:2:284)
    at __puppeteer_evaluation_script__:4:48
    at ExecutionContext._evaluateInternal (/home/matheus/whatsapp_connector/source/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/home/matheus/whatsapp_connector/source/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/matheus/whatsapp_connector/source/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/home/matheus/whatsapp_connector/source/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/home/matheus/whatsapp_connector/source/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/home/matheus/whatsapp_connector/source/node_modules/puppeteer/lib/Page.js:858:43)
    at Page.<anonymous> (/home/matheus/whatsapp_connector/source/node_modules/puppeteer/lib/helper.js:112:23)
    at Object.<anonymous> (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:84:39)
    at step (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:33:23)
    at Object.next (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:14:53)
    at /home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:4:12)
    at Object.retrieveQR (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:78:12)
    at Object.<anonymous> (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:77:55)
    at step (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:33:23)
    at Object.next (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:14:53)
    at /home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:4:12)
    at qrLoop (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:70:51)
    at Object.<anonymous> (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:98:21)
    at step (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:33:23)
    at Object.next (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:14:53)
    at fulfilled (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:5:58)
    at runMicrotasks (<anonymous>)
  -- ASYNC --
    at Page.<anonymous> (/home/matheus/whatsapp_connector/source/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:84:39)
    at step (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:33:23)
    at Object.next (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:14:53)
    at /home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:4:12)
    at Object.retrieveQR (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/auth.js:78:12)
    at Object.<anonymous> (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:77:55)
    at step (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:33:23)
    at Object.next (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:14:53)
    at /home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:4:12)
    at qrLoop (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:70:51)
    at Object.<anonymous> (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:98:21)
    at step (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:33:23)
    at Object.next (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:14:53)
    at fulfilled (/home/matheus/whatsapp_connector/source/node_modules/sulla-hotfix/dist/controllers/initializer.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11591) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11591) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**My code: (JS)**
(just a WIP version)
```javascript
const express = require('express');
const http = require('http');
const WebSocket = require('ws');
const sulla = require('sulla-hotfix');

const app = express();
const server = http.createServer(app);
const wss = new WebSocket.Server({server: server, clientTracking: true});

const uaOverride = 'WhatsApp/2.16.352 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15';

function WA_WS_client(wa, ws) {
    this.wa = wa;
    this.ws = ws;
}

var clients = {};

wss.on('connection', function(ws) {
    ws.send(JSON.stringify({
        type:'message',
        content: 'waiting for sessionId'
    }));

    ws.on('message', async function(message) {
        query = JSON.parse(message);
        if(query.type == 'sessionId') {
            if(query.sessionId in clients) {
                clients[query.sessionId].ws = ws;
                try {
                    if (clients[query.sessionId].wa.isConnected())
                        ws.send(JSON.stringify({
                            type: 'message',
                            content: 'Connected to WhatsApp server.'
                        }));
                    else
                        ws.send(JSON.stringify({
                            type: 'message',
                            content: 'Not connected to WhatsApp server.'
                        }));
                } catch (e) {
                    ws.send(JSON.stringify({
                        type: 'error',
                        content: 'No WhatsApp client for this sessionId'
                    }));

                }
            } else {
                ws.send(JSON.stringify({
                    type: 'message',
                    content: 'Creating a WhatsApp session.'
                }));
                var waClient = await sulla.create(query.sessionId,{executablePath: '/usr/bin/google-chrome-stable', headless: false},uaOverride);
                clients[query.sessionId] = new WA_WS_client(waClient,ws);
            }
        }
    });
});


server.listen(8080, function() {
    console.log('Server started on port 8080');
});

process.on('SIGINT', function() {
    try {
        clients.forEach((client) => {
            client.wa.kill();
        });
    } catch (e) {}
    server.close();
    console.log("Caught interrupt signal");
    process.exit();
});

```

**EDIT:** the demo program causes the same error (after correcting the paths...)

**Comment by rfscheidt** [comment]
I have the same error, it happen today.

**Comment by rfscheidt** [comment]
I tried to update to 1.6.13 and the message of error is different:

sapp foka$ node index.js 
⠋ Initializing whatsappserver is running ...
✔ Initializing whatsapp
⠋ Authenticating(node:31943) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'autoRefresh' of undefined
    at Object.<anonymous> (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/controllers/initializer.js:69:61)
    at step (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/controllers/initializer.js:33:23)
    at Object.next (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/controllers/initializer.js:14:53)
    at fulfilled (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/controllers/initializer.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:31943) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31943) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠙ Authenticating

**Comment by arturromaorocha** [comment]
![image](https://user-images.githubusercontent.com/11146355/73463310-6ab7d300-4353-11ea-814d-54d0327e70c2.png)

**Comment by smashah** [comment]
This is happening because in this new version of whatsapp, the state store is in some other address, not in 'eaaehfdjdg' as expected

**Comment by rfscheidt** [comment]
@smashah, in the version "sulla-hotfix": "^1.6.14", it is ok. Just apear an error at refresh qrcode.


(node:32366) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'qrRefreshS' of undefined
    at Object.<anonymous> (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/controllers/initializer.js:91:81)
    at step (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/controllers/initializer.js:33:23)
    at Object.next (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/controllers/initializer.js:14:53)
    at fulfilled (/Users/foka/dev/workspace-estudos/whatsapp/node_modules/sulla-hotfix/dist/controllers/initializer.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by smashah** [comment]
@rfscheidt Please try v1.6.15

It's a big change and should address the above issue and the qrRefreshS issue.
