### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by azisekk** [smashah/sulla#85]
**I have a problem**
Error: Cannot find module

sorry, its first time i'm using nodejs

how i can find a module? i'm get a error
```
(node:6856) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/esm/default_resolve.js:84
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module D:\Project\sulla-wa\src\index imported from D:\Project\sulla-wa\demo\run.js
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:84:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:147:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:41:40)
    at link (internal/modules/esm/module_job.js:40:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```
the contents of run.js are the same as demo/index.ts

please, i need help

**Comment by gnadelwartz** [comment]
demo is typescript you need typescript to run it, unfortunately @smashah  gas not documented ghus for newbies like us...

chnge the import statement to

```javascript
import { create, Whatsapp, decryptMedia, ev } from 'sulla-hotfix';
```

```bash
npm install -g ts-node
npm install -g typescript
ts-node example.ts
```

if you get a stating try to install `npm install xxx` install it ...

**Comment by azisekk** [comment]
> demo is typescript you need typescript to run it, unfortunately @smashah has not documented this for newbies like us...
> 
> change the import statement to
> 
> ```js
> import { create, Whatsapp, decryptMedia, ev } from 'sulla-hotfix';
> ```
> 
> then install typescript ...
> 
> ```shell
> npm install -g ts-node
> npm install -g typescript
> cp run.js run.ts
> ts-node run.ts
> ```
> 
> if you get errors stating try to install `npm install xxx` install it ...

i have been install all, but i still get an error
```
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
coba.ts:37:35 - error TS2339: Property 'forceRefocus' does not exist on type 'Whatsapp'.

37     if(state==="CONFLICT") client.forceRefocus();
                                     ~~~~~~~~~~~~

    at createTSError (C:\Users\Azis\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:421:12)
    at reportTSError (C:\Users\Azis\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:425:19)
    at getOutput (C:\Users\Azis\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:530:36)
    at Object.compile (C:\Users\Azis\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:735:32)
    at Module.m._compile (C:\Users\Azis\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:814:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Azis\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
```
how this?

**Comment by gnadelwartz** [comment]
do you have the newes sulla-hotfix version? alternatively comment out the complete section https://github.com/smashah/sulla/blob/3d7a0e6505b28e44db10a7aee1067fd376f7cfa6/demo/index.ts#L34-L38

**Comment by azisekk** [comment]
**solved**
it's work. 
thanks a lot
